ports:
  - port: 3000
    onOpen: open-preview
    visibility: public
tasks:
  - before: nvm install 16
    init: npm install
    command: npm run start


vscode:
  extensions:
    - esbenp.prettier-vscode
